#!/usr/bin/env bash

packages=(
  "libxcb-cursor-dev"
)

sudo apt install -y "${packages[@]}" --allow-change-held-packages

curl -fsSL https://install.danklinux.com | sh

cp -r ../niri $HOME/.config/
