source = ~/.config/hypr/env.conf
source = ~/.config/hypr/output.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybindings.conf
# ==================
# STARTUP APPS
# ==================
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = bash -c "wl-paste --watch cliphist store &"
env = WLR_RENDERER,gles3
