source = ~/.config/hypr/output.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/noctalia/noctalia-colors.conf

exec-once = wl-paste --watch cliphist store
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = qs -c noctalia-shell
source = ~/.config/hypr/noctalia/noctalia-colors.conf
