$mod = SUPER

bind = $mod, Return, exec, alacritty
bind = $mod, B, exec, brave %U
bind = $mod, space, exec, qs -c noctalia-shell ipc call launcher toggle
bind = $mod, Z, exec, qs -c noctalia-shell ipc call notifications toggleDND

# === Security ===
bind = $mod, L, exec, qs -c noctalia-shell ipc call lockScreen lock 
bind = $mod SHIFT, E, exit

# === Audio controls ===
bindel = , XF86AudioRaiseVolume, exec, qs -c noctalia-shell ipc call volume increase
bindel = , XF86AudioLowerVolume, exec, qs -c noctalia-shell ipc call volume decrease
bindl = , XF86AudioMute, exec, qs -c noctalia-shell ipc call volume muteOutput
bindl = , XF86Open, exec, qs -c noctalia-shell ipc call volume muteInput

# === Brightness controls ===
bindel = , XF86MonBrightnessUp, exec, qs -c noctalia-shell ipc call brightness increase
bindel = , XF86MonBrightnessDown, exec, qs -c noctalia-shell ipc call brightness decrease

# === Window Management ===
bind = $mod, W, killactive
bind = $mod, F, fullscreen, 1
bind = $mod, V, togglefloating

# === Focus Navigation ===
bind = $mod, left, cyclenext, prev
bind = $mod, right, cyclenext,

# === Window Movement ===
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r

bind = $mod, X, movecurrentworkspacetomonitor, -1
bind = $mod, Tab, focusmonitor, -1

bind = $mod, H, movetoworkspacesilent, special,
bind = $mod SHIFT, H, togglespecialworkspace,

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspacesilent, 1
bind = $mod SHIFT, 2, movetoworkspacesilent, 2
bind = $mod SHIFT, 3, movetoworkspacesilent, 3
bind = $mod SHIFT, 4, movetoworkspacesilent, 4
bind = $mod SHIFT, 5, movetoworkspacesilent, 5


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -
