windowrulev2 = float, class:^(xdg-desktop-portal)$

# DMS windows floating by default
windowrulev2 = float, class:^(org.quickshell)$
windowrulev2 = opacity 0.9 0.9, floating:0, focus:0

layerrule = noanim, ^(quickshell)$
